//! WS63 firmware source from validated IR. No unverified peripheral APIs.
use flow_core::{validate, Diagnostic};
use flow_ir::{BinaryOp, Expr, Program, Stmt};
use std::fmt::Write;

pub const BUILD_GN: &str = "# Integrate into the exact official SDK revision\nstatic_library(\"pyoh_flow\") {\n  sources = [ \"pyoh_flow.c\" ]\n  include_dirs = [ \"//base/startup/init/interfaces/innerkits\" ]\n}\n";

fn c_quote(value: &str) -> String {
    let mut escaped=String::from("\"");
    for c in value.chars() {
        match c {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            c if c.is_control() => { for b in c.to_string().as_bytes() {write!(escaped,"\\{:03o}",b).unwrap();} },
            c => escaped.push(c),
        }
    }
    escaped.push('"');
    escaped
}
fn expr(e:&Expr)->String {
    match e {
        Expr::Int{value}=>value.to_string(),
        Expr::Bool{value}=>if *value{"1"}else{"0"}.into(),
        Expr::Not{value}=>format!("(!{})",expr(value)),
        Expr::Binary{op,left,right}=>{
            let operator=match op {BinaryOp::Add=>"+",BinaryOp::Sub=>"-",BinaryOp::Mul=>"*",BinaryOp::Div=>"/",BinaryOp::Eq=>"==",BinaryOp::Ne=>"!=",BinaryOp::Lt=>"<",BinaryOp::Le=>"<=",BinaryOp::Gt=>">",BinaryOp::Ge=>">=",BinaryOp::And=>"&&",BinaryOp::Or=>"||"};
            format!("({} {} {})",expr(left),operator,expr(right))
        }
    }
}
fn emit(body:&[Stmt],depth:usize,index:&mut usize,out:&mut String){
    let tab="    ".repeat(depth);
    for statement in body {
        match statement {
            Stmt::Log{text,..} => {writeln!(out,"{tab}printf(\"[Flow] %s\\r\\n\", {});",c_quote(text)).unwrap();}
            Stmt::Sleep{millis,..} => {writeln!(out,"{tab}flow_sleep_ms({millis}U);").unwrap();}
            Stmt::Forever{body,..} => {
                writeln!(out,"{tab}while (1) {{").unwrap();
                emit(body,depth+1,index,out);
                writeln!(out,"{tab}    osDelay(1U); // yield").unwrap();
                writeln!(out,"{tab}}}").unwrap();
            }
            Stmt::Repeat{times,body,..} => {
                let i=*index;*index+=1;
                writeln!(out,"{tab}int32_t flow_count_{i} = {};",expr(times)).unwrap();
                writeln!(out,"{tab}if (flow_count_{i} > 100000) flow_count_{i} = 100000;").unwrap();
                writeln!(out,"{tab}for (int32_t flow_i_{i} = 0; flow_i_{i} < flow_count_{i}; ++flow_i_{i}) {{").unwrap();
                emit(body,depth+1,index,out);
                writeln!(out,"{tab}}}").unwrap();
            }
            Stmt::If{branches,otherwise,..} => {
                for (j,branch) in branches.iter().enumerate() {
                    writeln!(out,"{tab}{} ({}) {{",if j==0{"if"}else{"else if"},expr(&branch.condition)).unwrap();
                    emit(&branch.body,depth+1,index,out);
                    writeln!(out,"{tab}}}").unwrap();
                }
                if !otherwise.is_empty() {
                    writeln!(out,"{tab}else {{").unwrap();
                    emit(otherwise,depth+1,index,out);
                    writeln!(out,"{tab}}}").unwrap();
                }
            }
        }
    }
}
pub fn generate(program:&Program)->Result<String,Vec<Diagnostic>> {
    validate(program)?;
    let mut body=String::new();
    let mut index=0;
    emit(&program.body,1,&mut index,&mut body);
    Ok(format!(r#"/* Generated by XiaoHong Flow v0.3 Rust Core for first-generation WS63.
 * Integrate this C source in the official OpenHarmony SDK before flashing.
 */
#include <stdint.h>
#include <stdio.h>
#include "ohos_init.h"
#include "cmsis_os2.h"

static void flow_sleep_ms(uint32_t ms)
{{
    uint32_t hz = osKernelGetTickFreq();
    if (hz == 0U) return;
    uint64_t ticks = ((uint64_t)ms * hz + 999U) / 1000U;
    if (ticks == 0U) ticks = 1U;
    if (ticks > UINT32_MAX) ticks = UINT32_MAX;
    osDelay((uint32_t)ticks);
}}

static void FlowMain(void *arg)
{{
    (void)arg;
{body}}}

static void FlowStart(void)
{{
    const osThreadAttr_t attr = {{
        .name = "xiaohong_flow",
        .stack_size = 0x1000,
        .priority = osPriorityNormal,
    }};
    if (osThreadNew(FlowMain, NULL, &attr) == NULL) {{
        printf("[Flow] osThreadNew failed\r\n");
    }}
}}
APP_FEATURE_INIT(FlowStart);
"#))
}

#[cfg(test)]
mod tests {
    use super::*;
    use flow_ir::Target;
    #[test] fn generated_program_has_sdk_entry(){
        let p=Program{schema_version:1,target:Target::XiaohongWs63,body:vec![Stmt::Log{source_id:"log-1".into(),text:"Hi \"WS63\" %s\n".into()},Stmt::Sleep{source_id:"wait".into(),millis:1000}]};
        let c=generate(&p).unwrap();
        assert!(c.contains("APP_FEATURE_INIT(FlowStart)"));
        assert!(c.contains("osKernelGetTickFreq"));
        assert!(c.contains("printf(\"[Flow] %s\\r\\n\", \"Hi \\\"WS63\\\" %s\\n\")"));
    }
}
